// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mushus/activitypub"
	"github.com/Mushus/activitypub/sqlite"
	"github.com/rs/zerolog"
)

// Injectors from wire.go:

func createServer(log *zerolog.Logger) (*activitypub.Server, error) {
	config, err := activitypub.ParseConfig()
	if err != nil {
		return nil, err
	}
	urlResolver := activitypub.NewURLResolver(config)
	session, err := sqlite.NewSession()
	if err != nil {
		return nil, err
	}
	remoteServer := activitypub.NewRemoteServer(config, urlResolver)
	sqLite, err := sqlite.NewSQLite()
	if err != nil {
		return nil, err
	}
	accountStore := sqlite.NewAccountDB(sqLite)
	followStore := sqlite.NewFollowDB(sqLite)
	processor := activitypub.NewProcessor(config, log, urlResolver, remoteServer, accountStore, followStore)
	handler := activitypub.NewHandler(log, urlResolver, session, processor)
	server, err := activitypub.NewServer(config, handler)
	if err != nil {
		return nil, err
	}
	return server, nil
}
